//! Parameterized command workflows (v0.7 "Stitch").
//!
//! A [`Workflow`] is a named, reusable command template with `{{var}}`
//! placeholders. Users define workflows via the Command Palette or YAML
//! import; at runtime, variables are filled in via a form and the rendered
//! commands are submitted to the shell.
//!
//! ## Architecture
//!
//! - **Data model**: [`Workflow`] / [`WorkflowStep`] / [`WorkflowVar`] /
//!   [`WorkflowSource`] — pure data, fully serializable (serde + YAML).
//! - **Render engine**: [`Workflow::render`] replaces `{{var}}` with
//!   user-supplied values; [`Workflow::extract_var_names`] scans command
//!   templates for variables.
//! - **Persistence**: [`WorkflowStore`] wraps a SQLite connection (mirroring
//!   `persistence::BlockStore`). Workflows are the source-of-truth in the DB;
//!   YAML is only for import/export.

use std::collections::HashMap;
use std::path::Path;

use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};

// ── Data model ────────────────────────────────────────────────────────

/// Where a workflow originated. `Ai` is a forward-looking tag for v0.6
/// (AI-generated workflows); it has no behavioral effect today.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum WorkflowSource {
    /// User-created or imported from YAML.
    #[default]
    #[serde(rename = "manual")]
    Manual,
    /// Generated by an AI backend (v0.6+).
    #[serde(rename = "ai")]
    Ai,
}

/// A single variable definition within a workflow.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WorkflowVar {
    pub name: String,
    pub description: String,
    #[serde(default)]
    pub default: Option<String>,
    #[serde(default = "default_true")]
    pub required: bool,
}

fn default_true() -> bool {
    true
}

/// One command step in a workflow. A workflow may have multiple steps
/// executed sequentially. The `command` string may contain `{{var}}`
/// placeholders.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WorkflowStep {
    pub command: String,
}

/// A complete workflow definition — the unit of persistence and the data
/// behind the Command Palette workflow entries.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Workflow {
    /// SQLite primary key. 0 for unsaved/new workflows.
    #[serde(default)]
    pub id: i64,
    /// Unique short name used as the Command Palette search key (e.g. "deploy").
    pub name: String,
    /// Human-readable description shown in the palette.
    #[serde(default)]
    pub description: String,
    /// Ordered command steps. Variables are shared across all steps.
    #[serde(default)]
    pub steps: Vec<WorkflowStep>,
    /// Declared variables. If empty, [`extract_var_names`] is used to
    /// auto-discover `{{var}}` placeholders from the steps.
    #[serde(default)]
    pub variables: Vec<WorkflowVar>,
    /// Origin (manual or AI).
    #[serde(default)]
    pub source: WorkflowSource,
    /// How many times this workflow has been run (for palette sort order).
    #[serde(default)]
    pub use_count: i64,
    /// Last-run timestamp (Unix epoch millis).
    #[serde(default)]
    pub last_used_ms: i64,
}

// ── Render engine ────────────────────────────────────────────────────

/// Variable substitution failure.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum RenderError {
    #[error("missing required variable: {{{{{0}}}}}")]
    MissingRequired(String),
}

impl Workflow {
    /// Replace all `{{var}}` placeholders in every step with values from
    /// `values`. Resolution priority: `values` → `default` → error (if
    /// `required`) → empty string (if not required).
    ///
    /// Returns one rendered command string per step, in order.
    pub fn render(&self, values: &HashMap<String, String>) -> Result<Vec<String>, RenderError> {
        // First pass: check that every required DECLARED variable has a value.
        for var in &self.variables {
            let has_value = values.contains_key(&var.name) || var.default.is_some();
            if !has_value && var.required {
                return Err(RenderError::MissingRequired(var.name.clone()));
            }
        }

        // Build a lookup of declared variable defaults (name → default).
        let declared_defaults: HashMap<&str, Option<&str>> = self
            .variables
            .iter()
            .map(|v| (v.name.as_str(), v.default.as_deref()))
            .collect();

        // Second pass: replace ALL {{var}} in each step — both declared and
        // discovered (from the command text). This handles workflows created
        // via the UI editor which store variables: vec![] but have {{var}}
        // placeholders in their commands.
        let mut rendered = Vec::with_capacity(self.steps.len());
        for step in &self.steps {
            let mut cmd = step.command.clone();
            // Collect all var names that appear in this step's command.
            let var_names = {
                let mut names = Vec::new();
                scan_var_names(&step.command, &mut names);
                names
            };
            for name in &var_names {
                let val = values
                    .get(name)
                    .cloned()
                    .or_else(|| {
                        declared_defaults
                            .get(name.as_str())
                            .and_then(|d| d.map(String::from))
                    })
                    .unwrap_or_default();
                cmd = cmd.replace(&format!("{{{{{}}}}}", name), &val);
            }
            rendered.push(cmd);
        }
        Ok(rendered)
    }

    /// Extract all `{{var}}` names from the step commands. Used to auto-generate
    /// the variable form when `self.variables` is empty or incomplete.
    pub fn extract_var_names(&self) -> Vec<String> {
        let mut names: Vec<String> = Vec::new();
        for step in &self.steps {
            scan_var_names(&step.command, &mut names);
        }
        names
    }

    /// All variable names that need a form field: declared variables first
    /// (preserving their order/metadata), then any undiscovered `{{var}}`
    /// placeholders not in the declared list.
    pub fn all_var_names(&self) -> Vec<String> {
        let declared: Vec<String> = self.variables.iter().map(|v| v.name.clone()).collect();
        let mut all = declared.clone();
        for discovered in self.extract_var_names() {
            if !all.contains(&discovered) {
                all.push(discovered);
            }
        }
        all
    }
}

/// Scan `text` for `{{name}}` patterns, appending unique names to `out`.
fn scan_var_names(text: &str, out: &mut Vec<String>) {
    let bytes = text.as_bytes();
    let mut i = 0;
    while i + 1 < bytes.len() {
        if bytes[i] == b'{' && bytes[i + 1] == b'{' {
            // Find the closing }}.
            if let Some(end) = text[i + 2..].find("}}") {
                let name = text[i + 2..i + 2 + end].trim().to_string();
                if !name.is_empty() && !out.contains(&name) {
                    out.push(name);
                }
                i = i + 2 + end + 2;
                continue;
            }
        }
        i += 1;
    }
}

// ── WorkflowStore (SQLite persistence) ───────────────────────────────

/// Errors from the workflow store: filesystem or SQLite.
#[derive(Debug, thiserror::Error)]
pub enum WorkflowStoreError {
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("sqlite error: {0}")]
    Sqlite(#[from] rusqlite::Error),
    #[error("json error: {0}")]
    Json(#[from] serde_json::Error),
    #[error("yaml error: {0}")]
    Yaml(#[from] serde_yaml::Error),
}

/// SQLite-backed store of workflow definitions. Mirrors `BlockStore` in
/// design: one `rusqlite::Connection`, idempotent schema, synchronous I/O.
pub struct WorkflowStore {
    conn: Connection,
}

const SCHEMA: &str = "\
CREATE TABLE IF NOT EXISTS workflows (\
    id             INTEGER PRIMARY KEY AUTOINCREMENT,\
    name           TEXT NOT NULL UNIQUE,\
    description    TEXT NOT NULL DEFAULT '',\
    steps_json     TEXT NOT NULL,\
    variables_json TEXT NOT NULL,\
    source         TEXT NOT NULL DEFAULT 'manual',\
    use_count      INTEGER NOT NULL DEFAULT 0,\
    last_used_ms   INTEGER NOT NULL DEFAULT 0,\
    created_ms     INTEGER NOT NULL DEFAULT 0\
);\
CREATE INDEX IF NOT EXISTS idx_workflows_name ON workflows(name);\
CREATE INDEX IF NOT EXISTS idx_workflows_use ON workflows(use_count DESC, last_used_ms DESC);";

impl WorkflowStore {
    /// Open (creating if needed) the workflow DB at `path`.
    pub fn open(path: &Path) -> Result<Self, WorkflowStoreError> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let conn = Connection::open(path)?;
        conn.execute_batch(SCHEMA)?;
        Ok(Self { conn })
    }

    /// Insert a new workflow. Returns the assigned `id`.
    pub fn insert(&self, wf: &Workflow) -> Result<i64, WorkflowStoreError> {
        let steps_json = serde_json::to_string(&wf.steps)?;
        let variables_json = serde_json::to_string(&wf.variables)?;
        let source = match wf.source {
            WorkflowSource::Manual => "manual",
            WorkflowSource::Ai => "ai",
        };
        let created_ms = current_millis();
        self.conn.execute(
            "INSERT INTO workflows (name, description, steps_json, variables_json, source, use_count, last_used_ms, created_ms) \
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
            params![
                &wf.name,
                &wf.description,
                &steps_json,
                &variables_json,
                source,
                wf.use_count,
                wf.last_used_ms,
                created_ms,
            ],
        )?;
        Ok(self.conn.last_insert_rowid())
    }

    /// Update an existing workflow by id.
    pub fn update(&self, wf: &Workflow) -> Result<(), WorkflowStoreError> {
        let steps_json = serde_json::to_string(&wf.steps)?;
        let variables_json = serde_json::to_string(&wf.variables)?;
        let source = match wf.source {
            WorkflowSource::Manual => "manual",
            WorkflowSource::Ai => "ai",
        };
        self.conn.execute(
            "UPDATE workflows SET name=?2, description=?3, steps_json=?4, variables_json=?5, source=?6 \
             WHERE id=?1",
            params![
                wf.id,
                &wf.name,
                &wf.description,
                &steps_json,
                &variables_json,
                source,
            ],
        )?;
        Ok(())
    }

    /// Delete by id.
    pub fn delete(&self, id: i64) -> Result<(), WorkflowStoreError> {
        self.conn
            .execute("DELETE FROM workflows WHERE id=?1", params![id])?;
        Ok(())
    }

    /// Find by unique name.
    pub fn find_by_name(&self, name: &str) -> Result<Option<Workflow>, WorkflowStoreError> {
        let mut stmt = self.conn.prepare(
            "SELECT id, name, description, steps_json, variables_json, source, use_count, last_used_ms \
             FROM workflows WHERE name=?1",
        )?;
        let row = stmt.query_row(params![name], row_to_workflow).ok();
        Ok(row)
    }

    /// List all workflows, sorted by use frequency (most-used first).
    pub fn list(&self) -> Result<Vec<Workflow>, WorkflowStoreError> {
        let mut stmt = self.conn.prepare(
            "SELECT id, name, description, steps_json, variables_json, source, use_count, last_used_ms \
             FROM workflows ORDER BY use_count DESC, last_used_ms DESC, name ASC",
        )?;
        let rows = stmt.query_map([], row_to_workflow)?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    /// Case-insensitive substring search on name or description.
    pub fn search(&self, query: &str, limit: usize) -> Result<Vec<Workflow>, WorkflowStoreError> {
        // INSTR does a literal substring match (not LIKE pattern), so no % wildcards.
        let mut stmt = self.conn.prepare(
            "SELECT id, name, description, steps_json, variables_json, source, use_count, last_used_ms \
             FROM workflows \
             WHERE INSTR(LOWER(name), LOWER(?1)) > 0 OR INSTR(LOWER(description), LOWER(?1)) > 0 \
             ORDER BY use_count DESC, last_used_ms DESC LIMIT ?2",
        )?;
        let rows = stmt.query_map(params![query, limit as i64], row_to_workflow)?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    /// Increment use count and update last_used_ms.
    pub fn bump_use_count(&self, id: i64) -> Result<(), WorkflowStoreError> {
        self.conn.execute(
            "UPDATE workflows SET use_count = use_count + 1, last_used_ms = ?2 WHERE id=?1",
            params![id, current_millis()],
        )?;
        Ok(())
    }

    /// Total number of stored workflows (for seed-data detection).
    pub fn count(&self) -> Result<i64, WorkflowStoreError> {
        let count: i64 = self
            .conn
            .query_row("SELECT COUNT(*) FROM workflows", [], |row| row.get(0))?;
        Ok(count)
    }

    // ── YAML import / export ──────────────────────────────────────────

    /// Import a workflow from YAML text. Creates a new workflow or updates
    /// an existing one if the name matches. Returns the workflow id.
    pub fn import_yaml(&self, yaml: &str) -> Result<i64, WorkflowStoreError> {
        let wf: Workflow = serde_yaml::from_str(yaml)?;
        // Check if a workflow with this name already exists.
        if let Some(existing) = self.find_by_name(&wf.name)? {
            let mut updated = wf.clone();
            updated.id = existing.id;
            self.update(&updated)?;
            Ok(existing.id)
        } else {
            self.insert(&wf)
        }
    }

    /// Export a workflow as YAML text.
    pub fn export_yaml(&self, id: i64) -> Result<String, WorkflowStoreError> {
        let mut stmt = self.conn.prepare(
            "SELECT id, name, description, steps_json, variables_json, source, use_count, last_used_ms \
             FROM workflows WHERE id=?1",
        )?;
        let wf = stmt.query_row(params![id], row_to_workflow)?;
        Ok(serde_yaml::to_string(&wf)?)
    }
}

/// Decode a SQLite row into a [`Workflow`].
fn row_to_workflow(row: &rusqlite::Row) -> rusqlite::Result<Workflow> {
    let id: i64 = row.get(0)?;
    let name: String = row.get(1)?;
    let description: String = row.get(2)?;
    let steps_json: String = row.get(3)?;
    let variables_json: String = row.get(4)?;
    let source_str: String = row.get(5)?;
    let use_count: i64 = row.get(6)?;
    let last_used_ms: i64 = row.get(7)?;

    let steps: Vec<WorkflowStep> = serde_json::from_str(&steps_json).unwrap_or_default();
    let variables: Vec<WorkflowVar> = serde_json::from_str(&variables_json).unwrap_or_default();
    let source = match source_str.as_str() {
        "ai" => WorkflowSource::Ai,
        _ => WorkflowSource::Manual,
    };

    Ok(Workflow {
        id,
        name,
        description,
        steps,
        variables,
        source,
        use_count,
        last_used_ms,
    })
}

/// Current Unix epoch millis.
fn current_millis() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

// ── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    static TEMP_STORE_COUNTER: AtomicUsize = AtomicUsize::new(0);

    fn wf(name: &str, command: &str, vars: Vec<(&str, Option<&str>, bool)>) -> Workflow {
        Workflow {
            id: 0,
            name: name.to_string(),
            description: format!("Test workflow {name}"),
            steps: vec![WorkflowStep {
                command: command.to_string(),
            }],
            variables: vars
                .into_iter()
                .map(|(n, d, r)| WorkflowVar {
                    name: n.to_string(),
                    description: String::new(),
                    default: d.map(String::from),
                    required: r,
                })
                .collect(),
            source: WorkflowSource::Manual,
            use_count: 0,
            last_used_ms: 0,
        }
    }

    // ── Render engine tests ───────────────────────────────────────────

    #[test]
    fn render_replaces_variables() {
        let w = wf(
            "deploy",
            "docker up --scale {{scale}}",
            vec![("scale", Some("2"), true)],
        );
        let mut values = HashMap::new();
        values.insert("scale".to_string(), "5".to_string());
        let rendered = w.render(&values).unwrap();
        assert_eq!(rendered, vec!["docker up --scale 5"]);
    }

    #[test]
    fn render_uses_default_when_value_absent() {
        let w = wf("dev", "cd {{dir}}", vec![("dir", Some("."), true)]);
        let rendered = w.render(&HashMap::new()).unwrap();
        assert_eq!(rendered, vec!["cd ."]);
    }

    #[test]
    fn render_substitutes_undeclared_vars_from_command() {
        // Workflows created via the UI editor have variables: vec![] but
        // may contain {{var}} placeholders. render() must still substitute
        // them using values from the form.
        let w = Workflow {
            id: 0,
            name: "test".into(),
            description: String::new(),
            steps: vec![WorkflowStep {
                command: "echo {{msg}}".into(),
            }],
            variables: vec![], // empty — no declared variables
            source: WorkflowSource::Manual,
            use_count: 0,
            last_used_ms: 0,
        };
        let mut values = HashMap::new();
        values.insert("msg".to_string(), "hello".to_string());
        let rendered = w.render(&values).unwrap();
        assert_eq!(rendered, vec!["echo hello"]);
    }

    #[test]
    fn render_undeclared_var_without_value_becomes_empty() {
        // Undeclared var with no value → empty string (not required, no default).
        let w = Workflow {
            id: 0,
            name: "test".into(),
            description: String::new(),
            steps: vec![WorkflowStep {
                command: "echo [{{opt}}]".into(),
            }],
            variables: vec![],
            source: WorkflowSource::Manual,
            use_count: 0,
            last_used_ms: 0,
        };
        let rendered = w.render(&HashMap::new()).unwrap();
        assert_eq!(rendered, vec!["echo []"]);
    }

    #[test]
    fn render_errors_on_missing_required() {
        let w = wf("test", "echo {{x}}", vec![("x", None, true)]);
        let err = w.render(&HashMap::new()).unwrap_err();
        assert_eq!(err, RenderError::MissingRequired("x".to_string()));
    }

    #[test]
    fn render_empty_string_for_optional_missing() {
        let w = wf("test", "echo [{{opt}}]", vec![("opt", None, false)]);
        let rendered = w.render(&HashMap::new()).unwrap();
        assert_eq!(rendered, vec!["echo []"]);
    }

    #[test]
    fn render_multi_step_shares_variables() {
        let w = Workflow {
            id: 0,
            name: "multi".into(),
            description: String::new(),
            steps: vec![
                WorkflowStep {
                    command: "echo {{x}}".into(),
                },
                WorkflowStep {
                    command: "echo {{x}} again".into(),
                },
            ],
            variables: vec![WorkflowVar {
                name: "x".into(),
                description: String::new(),
                default: Some("v".into()),
                required: true,
            }],
            source: WorkflowSource::Manual,
            use_count: 0,
            last_used_ms: 0,
        };
        let rendered = w.render(&HashMap::new()).unwrap();
        assert_eq!(rendered, vec!["echo v", "echo v again"]);
    }

    // ── extract_var_names tests ───────────────────────────────────────

    #[test]
    fn extract_var_names_finds_placeholders() {
        let w = wf("test", "cd {{project}} && npm run {{script}}", vec![]);
        let names = w.extract_var_names();
        assert_eq!(names, vec!["project", "script"]);
    }

    #[test]
    fn extract_var_names_handles_no_vars() {
        let w = wf("test", "git status", vec![]);
        assert!(w.extract_var_names().is_empty());
    }

    #[test]
    fn extract_var_names_deduplicates() {
        let w = Workflow {
            id: 0,
            name: "t".into(),
            description: String::new(),
            steps: vec![
                WorkflowStep {
                    command: "echo {{x}}".into(),
                },
                WorkflowStep {
                    command: "echo {{x}}".into(),
                },
            ],
            variables: vec![],
            source: WorkflowSource::Manual,
            use_count: 0,
            last_used_ms: 0,
        };
        let names = w.extract_var_names();
        assert_eq!(names, vec!["x"]);
    }

    #[test]
    fn all_var_names_merges_declared_and_discovered() {
        let w = Workflow {
            id: 0,
            name: "t".into(),
            description: String::new(),
            steps: vec![WorkflowStep {
                command: "echo {{declared}} {{hidden}}".into(),
            }],
            variables: vec![WorkflowVar {
                name: "declared".into(),
                description: String::new(),
                default: None,
                required: true,
            }],
            source: WorkflowSource::Manual,
            use_count: 0,
            last_used_ms: 0,
        };
        let names = w.all_var_names();
        assert_eq!(names, vec!["declared", "hidden"]);
    }

    // ── WorkflowStore tests ───────────────────────────────────────────

    fn temp_store() -> WorkflowStore {
        let path = std::env::temp_dir().join(format!(
            "weft-workflow-{}-{}-{}.db",
            std::process::id(),
            TEMP_STORE_COUNTER.fetch_add(1, Ordering::Relaxed),
            std::time::SystemTime::UNIX_EPOCH
                .elapsed()
                .unwrap_or_default()
                .as_nanos()
        ));
        let _ = std::fs::remove_file(&path);
        WorkflowStore::open(&path).expect("open temp store")
    }

    #[test]
    fn store_insert_and_find_by_name() {
        let store = temp_store();
        let w = wf("deploy", "docker up", vec![]);
        let id = store.insert(&w).unwrap();
        assert!(id > 0);

        let found = store.find_by_name("deploy").unwrap().unwrap();
        assert_eq!(found.name, "deploy");
        assert_eq!(found.steps.len(), 1);
        assert_eq!(found.steps[0].command, "docker up");
    }

    #[test]
    fn store_update_changes_fields() {
        let store = temp_store();
        let id = store.insert(&wf("dev", "npm run", vec![])).unwrap();
        let mut updated = store.find_by_name("dev").unwrap().unwrap();
        updated.description = "Updated description".into();
        updated.steps[0].command = "npm run dev".into();
        store.update(&updated).unwrap();

        let found = store.find_by_name("dev").unwrap().unwrap();
        assert_eq!(found.description, "Updated description");
        assert_eq!(found.steps[0].command, "npm run dev");
        assert_eq!(found.id, id);
    }

    #[test]
    fn store_delete_removes_workflow() {
        let store = temp_store();
        let id = store.insert(&wf("temp", "echo hi", vec![])).unwrap();
        assert!(store.find_by_name("temp").unwrap().is_some());
        store.delete(id).unwrap();
        assert!(store.find_by_name("temp").unwrap().is_none());
    }

    #[test]
    fn store_list_sorted_by_use_count() {
        let store = temp_store();
        // Insert two workflows, bump one's use_count.
        let id_a = store.insert(&wf("alpha", "echo a", vec![])).unwrap();
        let _id_b = store.insert(&wf("beta", "echo b", vec![])).unwrap();
        store.bump_use_count(id_a).unwrap();
        store.bump_use_count(id_a).unwrap();

        let list = store.list().unwrap();
        assert_eq!(list.len(), 2);
        assert_eq!(list[0].name, "alpha"); // used more
        assert_eq!(list[0].use_count, 2);
        assert_eq!(list[1].name, "beta");
        assert_eq!(list[1].use_count, 0);
    }

    #[test]
    fn store_search_matches_name_or_description() {
        let store = temp_store();
        // Note: wf() sets description to "Test workflow {name}".
        store
            .insert(&wf("deploy", "docker compose up", vec![]))
            .unwrap();
        store.insert(&wf("logs", "tail -f log", vec![])).unwrap();

        // Search by name substring.
        let results = store.search("dep", 10).unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].name, "deploy");

        // Search by description substring ("Test workflow deploy").
        let results = store.search("deploy", 10).unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].name, "deploy"); // matches description

        // "logs" only in name, not description of other workflow.
        let results = store.search("log", 10).unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].name, "logs");
    }

    #[test]
    fn store_bump_use_count_increments() {
        let store = temp_store();
        let id = store.insert(&wf("test", "echo", vec![])).unwrap();
        store.bump_use_count(id).unwrap();
        let found = store.find_by_name("test").unwrap().unwrap();
        assert_eq!(found.use_count, 1);
        assert!(found.last_used_ms > 0);
    }

    #[test]
    fn store_count_reflects_insertions() {
        let store = temp_store();
        assert_eq!(store.count().unwrap(), 0);
        store.insert(&wf("a", "echo", vec![])).unwrap();
        store.insert(&wf("b", "echo", vec![])).unwrap();
        assert_eq!(store.count().unwrap(), 2);
    }

    // ── YAML import/export tests ──────────────────────────────────────

    #[test]
    fn yaml_export_roundtrip() {
        let store = temp_store();
        let id = store
            .insert(&wf(
                "deploy",
                "docker up --scale {{n}}",
                vec![("n", Some("2"), true)],
            ))
            .unwrap();
        let yaml = store.export_yaml(id).unwrap();
        assert!(yaml.contains("name: deploy"));
        assert!(yaml.contains("docker up"));

        // Re-import into a fresh store.
        let store2 = temp_store();
        let id2 = store2.import_yaml(&yaml).unwrap();
        let found = store2.find_by_name("deploy").unwrap().unwrap();
        assert_eq!(found.id, id2);
        assert_eq!(found.steps[0].command, "docker up --scale {{n}}");
        assert_eq!(found.variables.len(), 1);
        assert_eq!(found.variables[0].name, "n");
        assert_eq!(found.variables[0].default.as_deref(), Some("2"));
    }

    #[test]
    fn yaml_import_updates_existing_by_name() {
        let store = temp_store();
        store.insert(&wf("dev", "npm run", vec![])).unwrap();

        let yaml =
            "name: dev\ndescription: Updated\nsteps:\n  - command: npm run dev\nvariables: []\n";
        let id = store.import_yaml(yaml).unwrap();

        let found = store.find_by_name("dev").unwrap().unwrap();
        assert_eq!(found.id, id);
        assert_eq!(found.description, "Updated");
        assert_eq!(found.steps[0].command, "npm run dev");
    }

    #[test]
    fn yaml_minimal_valid() {
        let store = temp_store();
        let yaml =
            "name: sync\ndescription: git pull\nsteps:\n  - command: git pull\nvariables: []\n";
        let id = store.import_yaml(yaml).unwrap();
        let found = store.find_by_name("sync").unwrap().unwrap();
        assert_eq!(found.id, id);
        assert_eq!(found.steps.len(), 1);
    }
}
