name = "Everforest Dark Medium"
variant = "dark"
author = "Sainnhe Park (https://github.com/sainnhe)"
source = "tinted-theming/schemes/base16/everforest-dark-medium.yaml"
license = "MIT"

background = "#2d353b"
foreground = "#859289"
cursor = "#859289"
selection = "#3d484d"
palette = ["#343f44", "#e67e80", "#a7c080", "#dbbc7f", "#7fbbb3", "#d699b6", "#83c092", "#859289", "#475258", "#e67e80", "#a7c080", "#dbbc7f", "#7fbbb3", "#d699b6", "#83c092", "#d3c6aa"]
