name = "Flexoki Light"
variant = "light"
author = "Steph Ango (https://github.com/kepano/flexoki)"
source = "tinted-theming/schemes/base16/flexoki-light.yaml"
license = "MIT"

background = "#fffcf0"
foreground = "#403e3c"
cursor = "#403e3c"
selection = "#e6e4d9"
palette = ["#f2f0e5", "#af3029", "#66800b", "#ad8301", "#205ea6", "#5e409d", "#24837b", "#403e3c", "#cecdc3", "#af3029", "#66800b", "#ad8301", "#205ea6", "#5e409d", "#24837b", "#100f0f"]
