name = "Nord"
variant = "dark"
author = "arcticicestudio"
source = "tinted-theming/schemes/base16/nord.yaml"
license = "MIT"

background = "#2e3440"
foreground = "#e5e9f0"
cursor = "#e5e9f0"
selection = "#434c5e"
palette = ["#3b4252", "#bf616a", "#a3be8c", "#ebcb8b", "#81a1c1", "#b48ead", "#88c0d0", "#e5e9f0", "#4c566a", "#bf616a", "#a3be8c", "#ebcb8b", "#81a1c1", "#b48ead", "#88c0d0", "#8fbcbb"]
